#ifndef QNETWORKCLIQUERIES_GLOBAL_H
#define QNETWORKCLIQUERIES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QNETWORKCLIQUERIES_LIBRARY)
#  define QNETWORKCLIQUERIES_EXPORT Q_DECL_EXPORT
#else
#  define QNETWORKCLIQUERIES_EXPORT Q_DECL_IMPORT
#endif

#endif // QNETWORKCLIQUERIES_GLOBAL_H
