#ifndef QNETWORKQUERIESLOGGING_H
#define QNETWORKQUERIESLOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(queries)
Q_DECLARE_LOGGING_CATEGORY(queriesthread)
Q_DECLARE_LOGGING_CATEGORY(queriesthreadNeighbors)
Q_DECLARE_LOGGING_CATEGORY(queriesthreadController)

Q_DECLARE_LOGGING_CATEGORY(mplstetunnels)

#endif // QNETWORKQUERIESLOGGING_H
