---
equipo:
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    area_id:
      type: tinyint
      unsigned: true
    nombre:
      type: string(45)
      notnull: true
    ip:
      type: string(15)
      notnull: true
    estado:
      type: boolean
      notnull: true
  relations:
    area_1:
      foreignType: many
      foreignAlias: equipos
      local: area_id
      foreign: id
      class: area
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

interfaz:
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    equipo_id:
      type: integer
      unsigned: true
      notnull: true
    interfaz_tipo_id:
      type: tinyint
      unsigned: true
      notnull: true
    proveedor_id:
      type: string(3)
    interfaz:
      type: string(45)
      notnull: true
    bandwidth:
      type: bigint
      notnull: true
    descripcion:
      type: string(300)
    ospfcosto:
      type: integer
    estado:
      type: boolean
  relations:
    equipo_1:
      foreignType: many
      foreignAlias: interfazs
      local: equipo_id
      foreign: id
      class: equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION
    interfaz_tipo_2:
      foreignType: many
      foreignAlias: interfazs
      local: interfaz_tipo_id
      foreign: id
      class: interfaz_tipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION
    proveedor_3:
      foreignType: many
      foreignAlias: interfazs
      local: proveedor_id
      foreign: id
      class: proveedor
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

enlace:
  columns:
    id:
      type: bigint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    origen_interfaz_id:
      type: integer
      unsigned: true
      notnull: true
    destino_interfaz_id:
      type: integer
      unsigned: true
      notnull: true
    etiqueta:
      type: string(45)
    estado:
      type: boolean
  relations:
    interfaz_1:
      foreignType: many
      foreignAlias: enlaces
      local: origen_interfaz_id
      foreign: id
      class: interfaz
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION
    interfaz_2:
      foreignType: many
      foreignAlias: enlaces
      local: destino_interfaz_id
      foreign: id
      class: interfaz
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

grupo:
  columns:
    id:
      type: tinyint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    grupo:
      type: string(45)
      notnull: true

interfaz_tipo:
  columns:
    id:
      type: tinyint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    tipo:
      type: string(45)
      notnull: true

interfaz_estado:
  columns:
    id:
      type: bigint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    interfaz_id:
      type: integer
      unsigned: true
      notnull: true
    fecha:
      type: date
      notnull: true
    estado:
      type: boolean
      notnull: true
    ratein:
      type: bigint
      notnull: true
    rateout:
      type: bigint
      notnull: true
  relations:
    interfaz_1:
      foreignType: many
      foreignAlias: interfaz_estados
      local: interfaz_id
      foreign: id
      class: interfaz
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

area:
  columns:
    id:
      type: tinyint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    pais_id:
      type: tinyint
      unsigned: true
      notnull: true
    area:
      type: string(45)
      notnull: true
  relations:
    pais_1:
      foreignType: many
      foreignAlias: areas
      local: pais_id
      foreign: id
      class: pais
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

pais:
  columns:
    id:
      type: tinyint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    pais:
      type: string(45)
      notnull: true

proveedor:
  columns:
    id:
      type: string(3)
      primary: true
      notnull: true
    proveedor:
      type: string(45)
      notnull: true

grupo_equipo:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    grupo_id:
      type: tinyint
      unsigned: true
      notnull: true
    equipo_id:
      type: integer
      unsigned: true
      notnull: true
    posicion_x:
      type: float
    posicion_y:
      type: float
  relations:
    grupo_1:
      foreignType: many
      foreignAlias: grupo_equipos
      local: grupo_id
      foreign: id
      class: grupo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION
    equipo_2:
      foreignType: many
      foreignAlias: grupo_equipos
      local: equipo_id
      foreign: id
      class: equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

pcp_peer:
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    pcp_pais_id:
      type: tinyint
      unsigned: true
      notnull: true
    pcp_peer_tipo_id:
      type: tinyint
      unsigned: true
      notnull: true
    pcp_proveedor_id:
      type: integer
      unsigned: true
      notnull: true
    ip_pe:
      type: string(200)
      notnull: true
    vrf:
      type: string(100)
      notnull: true
    ip_peer:
      type: string(200)
      notnull: true
    comunidad_base:
      type: string(50)
      notnull: true
    estado:
      type: boolean
      notnull: true
    prefixin:
      type: integer
      unsigned: true
  relations:
    pcp_pais_1:
      foreignType: many
      foreignAlias: pcp_peers
      local: pcp_pais_id
      foreign: id
      class: pcp_pais
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION
    pcp_proveedor_2:
      foreignType: many
      foreignAlias: pcp_peers
      local: pcp_proveedor_id
      foreign: id
      class: pcp_proveedor
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION
    pcp_peer_tipo_3:
      foreignType: many
      foreignAlias: pcp_peers
      local: pcp_peer_tipo_id
      foreign: id
      class: pcp_peer_tipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

pcp_peer_tipo:
  columns:
    id:
      type: tinyint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    tipo:
      type: string(15)
      notnull: true

pcp_pais:
  columns:
    id:
      type: tinyint
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    pais:
      type: string(45)
      notnull: true
    pcp_region_id:
      type: integer
      notnull: true
  relations:
    pcp_region_1:
      foreignType: many
      foreignAlias: pcp_paiss
      local: pcp_region_id
      foreign: id
      class: pcp_region
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

pcp_proveedor:
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    proveedor:
      type: string(45)
      notnull: true
    logo_path:
      type: string(300)

pcp_pe:
  columns:
    id:
      type: integer
      unsigned: true
      primary: true
      notnull: true
      autoincrement: true
    nombre:
      type: string(45)
    ip:
      type: string(15)

pcp_region:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    region:
      type: string(45)

a9k_equipo:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_pais_id:
      type: integer
      notnull: true
    nombre:
      type: string(45)
      notnull: true
    IP:
      type: string(45)
      notnull: true
  relations:
    a9k_pais_1:
      foreignType: many
      foreignAlias: a9k_equipos
      local: a9k_pais_id
      foreign: id
      class: a9k_pais
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_slots:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    node:
      type: string(45)
    type:
      type: string(45)
    state:
      type: string(45)
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_slotss
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_memoria:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    fisica_total:
      type: integer
    fisica_disponible:
      type: integer
    app_disponible:
      type: integer
    bgp_limit:
      type: integer
    bgp:
      type: integer
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_memorias
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_energia:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    nmas1:
      type: tinyint
    bandeja0fuentes:
      type: smallint
    bandeja1fuentes:
      type: smallint
    capacidad_total:
      type: smallint
    total_requerido:
      type: smallint
    disponible:
      type: smallint
    cantidad_caida_fuentes_soportado:
      type: smallint
    no_soporta_caida_de_mas_de_una_fuente:
      type: tinyint
    cisco_capacidad_no_cableada:
      type: smallint
    cisco_caida_mitad_potencia_no_soportado:
      type: tinyint
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_energias
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_sesiones_cola:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    neighbor:
      type: string(45)
    inq:
      type: integer
    outq:
      type: integer
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_sesiones_colas
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_bgp_sesiones_weight:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    vrf:
      type: string(45)
    neighbor:
      type: string(45)
    routepolicy:
      type: string(100)
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_bgp_sesiones_weights
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_bgp_sesiones_sin_lp200:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    neighbor:
      type: string(45)
    prefixin:
      type: smallint
    routepolicy:
      type: string(45)
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_bgp_sesiones_sin_lp200s
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_mpls_label_table_summary:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    etiquetas_asignadas:
      type: integer
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_mpls_label_table_summarys
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_peer_caida_prefix_in:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    proveedor:
      type: string(45)
    neighbor:
      type: string(45)
    prefixin:
      type: integer
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_peer_caida_prefix_ins
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_internet_redistribucion_estaticas_conectadas:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    tipo:
      type: string(45)
    routepolicy:
      type: string(100)
    descripcion:
      type: string(100)
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_internet_redistribucion_estaticas_conectadass
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_vrf_sin_label_pervrf:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    vrf:
      type: string(45)
    address_family:
      type: string(45)
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_vrf_sin_label_pervrfs
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_bgp_inter_as:
  columns:
    date:
      type: date
      primary: true
      notnull: true
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    a9k_equipo_id:
      type: integer
      notnull: true
    neighbor:
      type: string(45)
    asn:
      type: string(45)
  relations:
    a9k_equipo_1:
      foreignType: many
      foreignAlias: a9k_bgp_inter_ass
      local: a9k_equipo_id
      foreign: id
      class: a9k_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

a9k_pais:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    pais:
      type: string(45)

ken_consulta:
  columns:
    id:
      type: bigint
      primary: true
      notnull: true
      autoincrement: true
    ken_equipo_id:
      type: integer
      notnull: true
    fecha:
      type: date
    destino_ip:
      type: string(45)
    max_bps:
      type: double
  relations:
    ken_equipo_1:
      foreignType: many
      foreignAlias: ken_consultas
      local: ken_equipo_id
      foreign: id
      class: ken_equipo
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

ken_equipo:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    ip:
      type: string(15)
      notnull: true
    nombre:
      type: string(45)
      notnull: true

red_consulta:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    red_sector_id:
      type: integer
      notnull: true
    fecha:
      type: date
      notnull: true
    ok:
      type: integer
    principalcaido:
      type: integer
    no:
      type: integer
    excepcion:
      type: integer
    noservicio:
      type: integer
    conexion_error:
      type: integer
    total:
      type: integer
  relations:
    red_sector_1:
      foreignType: many
      foreignAlias: red_consultas
      local: red_sector_id
      foreign: id
      class: red_sector
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

red_pais:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    pais:
      type: string(45)

red_consulta_detalle:
  columns:
    id:
      type: bigint
      primary: true
      notnull: true
      autoincrement: true
    red_sector_id:
      type: integer
      notnull: true
    fecha:
      type: date
    Principal_PE:
      type: string(100)
    Principal_Interface:
      type: string(45)
    VRF:
      type: string(45)
    IP:
      type: string(45)
    Respaldo_PE:
      type: string(100)
    Respaldo_Interface:
      type: string(45)
    Remoto_IP:
      type: string(45)
    Remoto_Interface:
      type: string(45)
    VCID_Principal:
      type: string(45)
    VCID_Principal_Estado:
      type: string(20)
    VCID_Respaldo:
      type: string(45)
    VCID_Respaldo_Estado:
      type: string(20)
    Redundancia:
      type: string(20)
    Descripcion:
      type: string(200)
    Detalle:
      type: string(200)
  relations:
    red_sector_1:
      foreignType: many
      foreignAlias: red_consulta_detalles
      local: red_sector_id
      foreign: id
      class: red_sector
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

TB_Addressing_consulta:
  columns:
    id:
      type: bigint
      primary: true
      notnull: true
      autoincrement: true
    Fecha:
      type: date
    Hostname:
      type: string(255)
    Interface:
      type: string(255)
    VRF:
      type: string(255)
    IP:
      type: string(255)

red_sector:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
      autoincrement: true
    red_pais_id:
      type: integer
      notnull: true
    sector:
      type: string(45)
  relations:
    red_pais_1:
      foreignType: many
      foreignAlias: red_sectors
      local: red_pais_id
      foreign: id
      class: red_pais
      owningSide: true
      onDelete: NO ACTION
      onUpdate: NO ACTION

