#ifndef QREMOTESHELL_GLOBAL_H
#define QREMOTESHELL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QREMOTESHELL_LIBRARY)
#  define QREMOTESHELLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QREMOTESHELLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QREMOTESHELL_GLOBAL_H
