#ifndef QREMOTESHELLLOGGING_H
#define QREMOTESHELLLOGGING_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(terminal)
Q_DECLARE_LOGGING_CATEGORY(qsshsession)
Q_DECLARE_LOGGING_CATEGORY(terminalReceived)
Q_DECLARE_LOGGING_CATEGORY(qremoteshell)


#endif // QREMOTESHELLLOGGING_H
