-- MySQL Script generated by MySQL Workbench
-- mar 21 ene 2020 17:05:11 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema unetadmin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subgrupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `subgrupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subgrupo_grupo1_idx` (`grupo_id` ASC),
  CONSTRAINT `fk_subgrupo_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `equipo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subgrupo_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `posicion_x` FLOAT NULL,
  `posicion_y` FLOAT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_equipo_subgrupo1_idx` (`subgrupo_id` ASC),
  CONSTRAINT `fk_equipo_subgrupo1`
    FOREIGN KEY (`subgrupo_id`)
    REFERENCES `subgrupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `interfaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `interfaz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `equipo_id` INT UNSIGNED NOT NULL,
  `interfaz` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_interfaz_equipo_idx` (`equipo_id` ASC),
  CONSTRAINT `fk_interfaz_equipo`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enlace` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `interfaz_id_origen` INT UNSIGNED NOT NULL,
  `interfaz_id_destino` INT UNSIGNED NOT NULL,
  `bandwidth` BIGINT NOT NULL,
  `fecha_operativo` DATE NOT NULL,
  `etiqueta` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enlace_interfaz1_idx` (`interfaz_id_origen` ASC),
  INDEX `fk_enlace_interfaz2_idx` (`interfaz_id_destino` ASC),
  CONSTRAINT `fk_enlace_interfaz1`
    FOREIGN KEY (`interfaz_id_origen`)
    REFERENCES `interfaz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enlace_interfaz2`
    FOREIGN KEY (`interfaz_id_destino`)
    REFERENCES `interfaz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enlace_estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enlace_estado` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `enlace_id` INT UNSIGNED NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `interfaz_origen_rateout` BIGINT NOT NULL,
  `interfaz_destino_rateout` BIGINT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enlace_estados_enlace1_idx` (`enlace_id` ASC),
  CONSTRAINT `fk_enlace_estados_enlace1`
    FOREIGN KEY (`enlace_id`)
    REFERENCES `enlace` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `grupo` (`id`, `grupo`) VALUES (NULL, 'Region'); 
INSERT INTO `subgrupo` (`id`, `grupo_id`, `subgrupo`) VALUES (NULL, '1', 'Region'); 

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
